<?xml version="1.0" encoding="UTF-8"?>
<!--===============================================================--><!--Vertex Inc O Series Health Check Services WSDL File--><!--===============================================================--><!--Schema author: Vertex Inc.
Schema version: 9.0
Schema date: 23 jan 2019
Copyright (C) Vertex Inc. (2017). All Rights Reserved.--><wsdl:definitions name="HealthCheck" targetNamespace="urn:vertexinc:oseries:ws:healthcheck:9:0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:vertexinc:oseries:ws:healthcheck:9:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema targetNamespace="urn:vertexinc:oseries:ws:healthcheck:9:0">
      <xsd:include schemaLocation="VertexIncHealthCheck_9_0.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="PerformHealthCheckRequest">
    <wsdl:part element="tns:PerformHealthCheckRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="PerformHealthCheckResponse">
    <wsdl:part element="tns:PerformHealthCheckResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="HealthCheckException">
    <wsdl:part element="tns:ServiceFault" name="fault"/>
  </wsdl:message>
  <wsdl:portType name="HealthCheckServicePortType">
    <wsdl:operation name="PerformHealthCheck">
      <wsdl:input message="tns:PerformHealthCheckRequest" name="performHealthCheckRequest"/>
      <wsdl:output message="tns:PerformHealthCheckResponse" name="performHealthCheckResponse"/>
      <wsdl:fault message="tns:HealthCheckException" name="healthCheckException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HealthCheckServiceBinding" type="tns:HealthCheckServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="PerformHealthCheck">
      <soap:operation soapAction=""/>
      <wsdl:input name="performHealthCheckRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="performHealthCheckResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="healthCheckException">
        <soap:fault name="healthCheckException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HealthCheckService">
    <wsdl:port binding="tns:HealthCheckServiceBinding" name="HealthCheckPort">
      <soap:address location="https://localhost:443/vertex-ws/adminservices/healthcheck90"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>