name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  MAVEN_FLAGS: "-B --no-transfer-progress"
  VERTEX_URL: ${{ secrets.VERTEX_URL }}
  VERTEX_CLIENT_ID: ${{ secrets.VERTEX_CLIENT_ID }}
  VERTEX_CLIENT_SECRET: ${{ secrets.VERTEX_CLIENT_SECRET }}
  VERTEX_COMPANY_NAME: ${{ secrets.VERTEX_COMPANY_NAME }}
  VERTEX_COMPANY_DIVISION: ${{ secrets.VERTEX_COMPANY_DIVISION }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
        java-distribution:
          - adopt
          - zulu
        profile:
          - travis
          - integration-mysql
          - integration-postgresql
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Configure Sonatype mirror
        uses: s4u/maven-settings-action@v2.3.0
        # Go to Sonatype directly to avoid delay syncs (could get rid of this if actions/setup-java were to support mirrors).
        with:
          mirrors: '[{"id": "oss-releases", "name": "Sonatype releases", "mirrorOf": "*", "url": "https://oss.sonatype.org/content/repositories/releases/"}]'
      - name: Tests
        env:
          MAVEN_PROFILE: ${{ matrix.profile }}
        run: |
          mvn ${MAVEN_FLAGS} clean install -P${MAVEN_PROFILE}